### ISSUE TITLE
モックを実装

### ISSUE THREAD

**Issue by nuno929** [team-maker-developers/admin#8]
# 概要
## 背景
- デモ版としての用途があるかもしれないので、mockを実装する
     - デザイナがjoinした際、mockがあれば、議論がしやすくなる

## 実装方針
- mockとして、バックエンドがなくても動作するよう仕組みを実装
     - mock用のプラグインを実装する
- バックエンドが未組込みの部分を実装する

**Comment by nuno929** [comment]
[![Netlify Status](https://api.netlify.com/api/v1/badges/4abb0641-6c64-4a32-b5e8-03d761a7fcff/deploy-status)](https://app.netlify.com/sites/tender-poitras-265ea2/deploys)

**Comment by daisuke85a** [comment]
以下を行っていきます。

- 参考にする競合サービスの調査（力をかけすぎないように）
- デザインカンプ作成
- デザインに関するヒアリング項目作成
- モック作成

**Comment by nuno929** [comment]
その認識で大丈夫です！

**Comment by daisuke85a** [comment]
vuetifyの勉強がてら、人事用のダッシュボード画面のモックを作っています〜。

**Comment by nuno929** [comment]
実画面ができたので、対応不要
